AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  智汇-ERP后端 (zhihui-erp-backend)

  一个为多租户ERP系统设计的、包含安全网络环境和正确Lambda配置的SAM模板。

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.11
    Architectures:
      - x86_64

Parameters:
  DBName:
    Type: String
    Default: jori_erp_db
    Description: RDS PostgreSQL 数据库的名称。
  DBUser:
    Type: String
    Default: postgres
    Description: RDS 数据库的主用户名。
  DBPassword:
    Type: String
    Default: test1234
    NoEcho: true
    Description: RDS 数据库的主密码。

Resources:
  # --- 网络基础设施 ---
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: 智汇ERP-VPC

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: 智汇ERP-公共子网A

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: 智汇ERP-私有子网A

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: 智汇ERP-互联网网关

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnetA
      Tags:
        - Key: Name
          Value: 智汇ERP-NAT网关

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: 智汇ERP-公共路由表

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: 智汇ERP-私有路由表

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable

  # --- 安全组 ---
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "为 Lambda 函数设计的安全组"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: 智汇ERP-Lambda安全组

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "为 RDS 实例设计的安全组"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
      Tags:
        - Key: Name
          Value: 智汇ERP-Rds安全组
  
  # --- 数据库 ---
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "为 RDS 设计的子网组"
      SubnetIds:
        - !Ref PrivateSubnetA

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: '15'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Tags:
        - Key: Name
          Value: 智汇ERP-DB实例

  SuperAdminSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "用于ERP后端的超级管理员凭证"
      SecretString: !Sub '{"username": "superadmin", "password": "test1234"}'

  # --- Lambda Layers ---
  DatabaseUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: zhihui-erp-db-utils-layer
      Description: "提供数据库连接和通用功能的共享工具层"
      ContentUri: backend/lambda/layers/database_utils
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain

  # --- Lambda 函数 ---
  DbSetupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: erp-db-setup-function
      CodeUri: backend/lambda/db_setup_assets/
      Handler: db_setup.handler
      Policies:
        - VPCAccessPolicy: {}
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
      Environment:
        Variables:
          DB_HOST: !GetAtt DBInstance.Endpoint.Address
          DB_PORT: !GetAtt DBInstance.Endpoint.Port
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: erp-auth-function
      CodeUri: backend/lambda/auth/
      Handler: auth.handler
      Layers:
        - !Ref DatabaseUtilsLayer
      Policies:
        - VPCAccessPolicy: {}
        - SecretsManagerReadWrite
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
      Environment:
        Variables:
          DB_HOST: !GetAtt DBInstance.Endpoint.Address
          DB_PORT: !GetAtt DBInstance.Endpoint.Port
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          JWT_SECRET: your_jwt_secret_here
          SUPER_ADMIN_SECRET_ARN: !Ref SuperAdminSecret
      Events:
        AuthApi:
          Type: Api
          Properties:
            Path: /auth/{proxy+}
            Method: ANY

  TenantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: erp-tenants-function
      CodeUri: backend/lambda/tenants/
      Handler: tenants.handler
      Layers:
        - !Ref DatabaseUtilsLayer
      Policies:
        - VPCAccessPolicy: {}
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
      Environment:
        Variables:
          DB_HOST: !GetAtt DBInstance.Endpoint.Address
          DB_PORT: !GetAtt DBInstance.Endpoint.Port
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          JWT_SECRET: your_jwt_secret_here
      Events:
        TenantsApi:
          Type: Api
          Properties:
            Path: /tenants
            Method: ANY

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: erp-users-function
      CodeUri: backend/lambda/users/
      Handler: users.handler
      Layers:
        - !Ref DatabaseUtilsLayer
      Policies:
        - VPCAccessPolicy: {}
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
      Environment:
        Variables:
          DB_HOST: !GetAtt DBInstance.Endpoint.Address
          DB_PORT: !GetAtt DBInstance.Endpoint.Port
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          JWT_SECRET: your_jwt_secret_here
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /users/{proxy+}
            Method: ANY

Outputs:
  ApiGatewayEndpoint:
    Description: "API 网关的根终端节点 URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  DbSetupFunctionName:
    Description: "DbSetup Lambda 函数的名称"
    Value: !Ref DbSetupFunction
  DBEndpoint:
    Description: "RDS 实例的终端节点地址"
    Value: !GetAtt DBInstance.Endpoint.Address
