AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  智汇-ERP后端 (zhihui-erp-backend) V3

  一个为多租户ERP系统设计的、采用现代HTTP API架构的SAM模板。

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.11
    Architectures:
      - x86_64

Parameters:
  DBName:
    Type: String
    Default: jori_erp_db
    Description: The name for the RDS PostgreSQL database.
  DBUser:
    Type: String
    Default: postgres
    Description: Master username for the RDS database.
  DBPassword:
    Type: String
    Default: test1234
    NoEcho: true
    Description: Master password for the RDS database.

Resources:
  ZhiHuiErpHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          # 诊断性配置，暂时允许所有来源
          - "*"
        AllowHeaders:
          - "Content-Type"
          - "Authorization"
        AllowMethods:
          # 明确允许预检请求所使用的OPTIONS方法
          - "GET"
          - "POST"
          - "OPTIONS"

  # --- Network Infrastructure (Omitted for brevity, unchanged) ---
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: 智汇ERP-VPC

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: 智汇ERP-公共子网A

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: 智汇ERP-私有子网A

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: 智汇ERP-公共子网B

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: 智汇ERP-私有子网B

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: 智汇ERP-互联网网关

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnetA
      Tags:
        - Key: Name
          Value: 智汇ERP-NAT网关

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: 智汇ERP-公共路由表

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: 智汇ERP-私有路由表

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRouteTable

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for Lambda functions"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: 智汇ERP-Lambda安全组

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for the RDS instance"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
      Tags:
        - Key: Name
          Value: 智汇ERP-Rds安全组
  
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for the RDS instance, covering multiple AZs"
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: '15'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: true
      Tags:
        - Key: Name
          Value: 智汇ERP-DB实例

  SuperAdminSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Super admin credentials for the ERP backend"
      SecretString: !Sub '{"username": "superadmin", "password": "test1234"}'

  DatabaseUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: zhihui-erp-db-utils-layer
      Description: "Shared utilities layer for database connections"
      ContentUri: backend/lambda/layers/database_utils
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11

  DbSetupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: erp-db-setup-function
      CodeUri: backend/lambda/db_setup_assets/
      Handler: db_setup.handler
      Layers:
        - !Ref DatabaseUtilsLayer
      Policies:
        - VPCAccessPolicy: {}
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Environment:
        Variables:
          DB_HOST: !GetAtt DBInstance.Endpoint.Address
          DB_PORT: !GetAtt DBInstance.Endpoint.Port
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: erp-auth-function
      CodeUri: backend/lambda/auth/
      Handler: auth.handler
      Layers:
        - !Ref DatabaseUtilsLayer
      Policies:
        - VPCAccessPolicy: {}
        - SecretsManagerReadWrite
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Environment:
        Variables:
          DB_HOST: !GetAtt DBInstance.Endpoint.Address
          DB_PORT: !GetAtt DBInstance.Endpoint.Port
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          JWT_SECRET: your_jwt_secret_here
          SUPER_ADMIN_SECRET_ARN: !Ref SuperAdminSecret
      Events:
        LoginApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ZhiHuiErpHttpApi
            Path: /api/auth/login
            Method: POST

  TenantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: erp-tenants-function
      CodeUri: backend/lambda/tenants/
      Handler: tenants.handler
      Layers:
        - !Ref DatabaseUtilsLayer
      Policies:
        - VPCAccessPolicy: {}
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Environment:
        Variables:
          DB_HOST: !GetAtt DBInstance.Endpoint.Address
          DB_PORT: !GetAtt DBInstance.Endpoint.Port
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          JWT_SECRET: your_jwt_secret_here
      Events:
        GetTenantsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ZhiHuiErpHttpApi
            Path: /api/tenants
            Method: GET
        CreateTenantApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ZhiHuiErpHttpApi
            Path: /api/tenants
            Method: POST

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: erp-users-function
      CodeUri: backend/lambda/users/
      Handler: users.handler
      Layers:
        - !Ref DatabaseUtilsLayer
      Policies:
        - VPCAccessPolicy: {}
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Environment:
        Variables:
          DB_HOST: !GetAtt DBInstance.Endpoint.Address
          DB_PORT: !GetAtt DBInstance.Endpoint.Port
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          JWT_SECRET: your_jwt_secret_here
      Events:
        # 出于完整性考虑，同样进行精确化改造
        ListUsersApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ZhiHuiErpHttpApi
            Path: /api/users
            Method: GET
        GetUserApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ZhiHuiErpHttpApi
            Path: /api/users/{userId}
            Method: GET

Outputs:
  ApiGatewayEndpoint:
    Description: "Root endpoint URL for the HTTP API Gateway"
    Value: !Sub "https://${ZhiHuiErpHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  DbSetupFunctionName:
    Description: "Name of the DbSetup Lambda function"
    Value: !Ref DbSetupFunction
  DBEndpoint:
    Description: "Endpoint address of the RDS instance"
    Value: !GetAtt DBInstance.Endpoint.Address
