
import React from 'react';
import { 
  LayoutDashboard, 
  Package, 
  ShoppingCart, 
  Warehouse, 
  Users, 
  User,
  Settings, 
  Bell, 
  Search, 
  Menu,
  TrendingUp,
  TrendingDown, 
  DollarSign,
  ClipboardList,
  UserPlus,
  Activity,
  ScanBarcode,
  Plus,
  Filter,
  MoreHorizontal,
  ChevronRight,
  ChevronDown,
  AlertTriangle,
  CheckCircle2,
  Trash2,
  CreditCard,
  Printer,
  FileText,
  Truck,
  ArrowLeftRight,
  Briefcase,
  PieChart,
  CheckSquare,
  Landmark,
  Tags,
  UserCog,
  FileSpreadsheet,
  ArrowUpRight,
  ArrowDownLeft,
  X,
  Banknote,
  Hourglass,
  Sparkles,
  ListPlus,
  Eye,
  MoreVertical,
  LogIn,
  LogOut,
  RefreshCw,
  Calendar,
  ClipboardCheck,
  QrCode,
  Code,
  Cloud,
  BellRing,
  Download,
  Undo2,
  Package2,
  Ban,
  Info,
  Save,
  ShoppingBag,
  Calculator,
  AlertCircle,
  ArrowLeft,
  Store,
  Upload,
  History,
  Image,
  MessageCircle,
  File,
  Phone,
  MapPin,
  LineChart,
  Home,
  PlusCircle,
  Lightbulb,
  FileBadge,
  Building2,
  Mail,
  PhoneCall,
  Wallet,
  Snowflake,
  Link,
  FileCheck,
  PlayCircle,
  Send,
  ShieldCheck,
  MinusCircle,
  FileEdit,
  PlusSquare,
  Delete,
  Target,
  ListOrdered,
  Star,
  Copy,
  Circle,
  Box,
  Sun,
  Inbox,
  List,
  Clock,
  Archive,
  Disc,
  Hammer,
  Zap,
  Palette,
  Signal,
  Wifi,
  Monitor,
  Smartphone,
  Lock,
  Rocket,
  CircleHelp,
  Headphones,
  LoaderCircle,
  Shield
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Product: Package,
  Package: Package,
  POS: ShoppingCart,
  ShoppingCart: ShoppingCart,
  Warehouse: Warehouse,
  Inventory: Package2,
  Package2: Package2,
  Users: Users,
  User: User,
  Settings: Settings,
  Bell: Bell,
  Search: Search,
  Menu: Menu,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  Dollar: DollarSign,
  Order: ClipboardList,
  ClipboardList: ClipboardList,
  NewUser: UserPlus,
  Activity: Activity,
  Scan: ScanBarcode,
  Plus: Plus,
  Filter: Filter,
  More: MoreHorizontal,
  MoreHorizontal: MoreHorizontal,
  MoreVertical: MoreVertical,
  ArrowRight: ChevronRight,
  ChevronRight: ChevronRight,
  ChevronDown: ChevronDown,
  ArrowLeft: ArrowLeft,
  Warning: AlertTriangle,
  AlertTriangle: AlertTriangle,
  Check: CheckCircle2,
  CheckCircle2: CheckCircle2,
  Delete: Trash2,
  Trash2: Trash2,
  Payment: CreditCard,
  CreditCard: CreditCard,
  Print: Printer,
  FileText: FileText,
  Truck: Truck,
  Transfer: ArrowLeftRight,
  Briefcase: Briefcase,
  Chart: PieChart,
  PieChart: PieChart,
  Approval: CheckSquare,
  CheckSquare: CheckSquare,
  Bank: Landmark,
  Category: Tags,
  Tags: Tags,
  UserEdit: UserCog,
  Report: FileSpreadsheet,
  FileSpreadsheet: FileSpreadsheet,
  Inbound: ArrowDownLeft,
  ArrowDownLeft: ArrowDownLeft,
  Outbound: ArrowUpRight,
  ArrowUpRight: ArrowUpRight,
  Close: X,
  Banknote: Banknote,
  Hourglass: Hourglass,
  Sparkles: Sparkles,
  ListPlus: ListPlus,
  Eye: Eye,
  LogIn: LogIn,
  LogOut: LogOut,
  Refresh: RefreshCw,
  RefreshCw: RefreshCw,
  Calendar: Calendar,
  ClipboardCheck: ClipboardCheck,
  QrCode: QrCode,
  Code: Code,
  Cloud: Cloud,
  BellRing: BellRing,
  Download: Download,
  Undo: Undo2,
  Ban: Ban,
  Info: Info,
  Save: Save,
  ShoppingBag: ShoppingBag,
  Calculator: Calculator,
  AlertCircle: AlertCircle,
  Store: Store,
  Upload: Upload,
  History: History,
  Image: Image,
  WeChat: MessageCircle,
  File: File,
  Phone: Phone,
  MapPin: MapPin,
  LineChart: LineChart,
  Home: Home,
  PlusCircle: PlusCircle,
  Lightbulb: Lightbulb,
  RequestQuote: FileBadge,
  Building: Building2,
  Mail: Mail,
  PhoneCall: PhoneCall,
  Wallet: Wallet,
  Snowflake: Snowflake,
  Link: Link,
  FileCheck: FileCheck,
  Play: PlayCircle,
  Send: Send,
  ShieldCheck: ShieldCheck,
  Minus: MinusCircle,
  FileEdit: FileEdit,
  PlusSquare: PlusSquare,
  DeleteSweep: Delete,
  Target: Target,
  ListOrdered: ListOrdered,
  Star: Star,
  Copy: Copy,
  Circle: Circle,
  Box: Box,
  Sun: Sun,
  Inbox: Inbox,
  List: List,
  Clock: Clock,
  Archive: Archive,
  Disc: Disc,
  Hammer: Hammer,
  Zap: Zap,
  Palette: Palette,
  Bag: ShoppingBag,
  Signal: Signal,
  Wifi: Wifi,
  Monitor: Monitor,
  Smartphone: Smartphone,
  Lock: Lock,
  Rocket: Rocket,
  HelpCircle: CircleHelp,
  Headphones: Headphones,
  LoaderCircle: LoaderCircle,
  Shield: Shield,
};
